<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \Illuminate\Support\Facades\DB::table('stunting_indicators')->insert([
            [
                'kab/kota' => 'Kab. Pacitan',
                'latitude' => -8.126331,
                'longitude' => 111.1414226,
                'stunting' => 28.5,
                'hamil' => 91.6,
                'tambah_darah' => 59.4,
                'persalinan_nakes' => 91.2,
                'vit_a' => 84.8,
                'bblr' => 6,
                'imd' => 72,
                'asi_baduta' => 100,
                'lama_asi' => 9.63,
                'asi_pendamping' => 4.92,
                'imunisasi' => 68.8,
                'vit_a_6_11' => 74.3,
                'vit_a_12_59' => 75.4,
                'vit_a_6_59' => 75.2,
                'cakupan' => 92.2,
                'jiwa_rt' => 3.05,
                'sanitasi' => 65.01,
                'air_minum' => 77.72,
                'ipm' => 68.16,
                'miskin' => 13.67,
                'lisa_cluster' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kab/kota' => 'Kab. Ponorogo',
                'latitude' => -7.8650759,
                'longitude' => 111.4696322,
                'stunting' => 26.9,
                'hamil' => 88.4,
                'tambah_darah' => 85.3,
                'persalinan_nakes' => 92.7,
                'vit_a' => 58.3,
                'bblr' => 4.8,
                'imd' => 37.2,
                'asi_baduta' => 96.92,
                'lama_asi' => 12.5,
                'asi_pendamping' => 7.52,
                'imunisasi' => 76.79,
                'vit_a_6_11' => 79.9,
                'vit_a_12_59' => 79.9,
                'vit_a_6_59' => 79.9,
                'cakupan' => 80.1,
                'jiwa_rt' => 2.97,
                'sanitasi' => 80.37,
                'air_minum' => 93.02,
                'ipm' => 70.56,
                'miskin' => 9.64,
                'lisa_cluster' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kab/kota' => 'Kab. Trenggalek',
                'latitude' => -8.1824112,
                'longitude' => 111.6183755,
                'stunting' => 25.9,
                'hamil' => 83.2,
                'tambah_darah' => 91.9,
                'persalinan_nakes' => 91.3,
                'vit_a' => 89.5,
                'bblr' => 4.5,
                'imd' => 62.1,
                'asi_baduta' => 96.68,
                'lama_asi' => 11.41,
                'asi_pendamping' => 6.91,
                'imunisasi' => 69.62,
                'vit_a_6_11' => 96.8,
                'vit_a_12_59' => 97,
                'vit_a_6_59' => 96.9,
                'cakupan' => 90.9,
                'jiwa_rt' => 3.06,
                'sanitasi' => 72.72,
                'air_minum' => 80.53,
                'ipm' => 69.46,
                'miskin' => 10.98,
                'lisa_cluster' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kab/kota' => 'Kab. Tulungagung',
                'latitude' => -8.0843211,
                'longitude' => 111.9045541,
                'stunting' => 30.6,
                'hamil' => 91.4,
                'tambah_darah' => 89,
                'persalinan_nakes' => 91.4,
                'vit_a' => 89.9,
                'bblr' => 3.1,
                'imd' => 61.9,
                'asi_baduta' => 94.51,
                'lama_asi' => 10.94,
                'asi_pendamping' => 6.65,
                'imunisasi' => 67.69,
                'vit_a_6_11' => 78.2,
                'vit_a_12_59' => 84.8,
                'vit_a_6_59' => 83.5,
                'cakupan' => 89.8,
                'jiwa_rt' => 3.1,
                'sanitasi' => 79.82,
                'air_minum' => 97.65,
                'ipm' => 72.62,
                'miskin' => 6.74,
                'lisa_cluster' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kab/kota' => 'Kab. Blitar',
                'latitude' => -8.1308657,
                'longitude' => 112.2200091,
                'stunting' => 25.4,
                'hamil' => 85,
                'tambah_darah' => 100,
                'persalinan_nakes' => 88,
                'vit_a' => 55.1,
                'bblr' => 3.9,
                'imd' => 47.1,
                'asi_baduta' => 97.89,
                'lama_asi' => 9.91,
                'asi_pendamping' => 5.85,
                'imunisasi' => 80.24,
                'vit_a_6_11' => 100.8,
                'vit_a_12_59' => 74.8,
                'vit_a_6_59' => 80,
                'cakupan' => 82.3,
                'jiwa_rt' => 2.98,
                'sanitasi' => 75.73,
                'air_minum' => 92.71,
                'ipm' => 70.57,
                'miskin' => 8.94,
                'lisa_cluster' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
